spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/qipai_guandan
      database: qipai_guandan
      host: dds-bp1f74084c1cd354118530.mongodb.rds.aliyuncs.com
      port: 3717
      username: root
      password: 'Meiyoumima!'
#      host: 172.16.57.175
#      port: 27025
#      username: root
#      password: '123456'
      authentication-database: admin
      repositories:
        enabled: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          guandanGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          guandanResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wisecrack:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          watchRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        guandanGame:
          destination: guandanGame
          contentType: application/json
          producer:
            partitionCount: 1
        guandanResult:
          destination: guandanResult
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-guandan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-guandan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        guandanGameRoom:
          destination: guandanGameRoom
          group: qipai-guandan
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wisecrack:
          destination: wisecrack
          contentType: application/json
          producer:
            partitionCount: 1
        watchRecord:
          destination: watchRecord
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-guandan

server:
  port: 2009
  context-path: /guandan
  connectionTimeout: 65000
  tomcat:
    max-connections: 1024
    max-threads: 1024
    access-log-enabled: true
    access-log-pattern: '%a %h %A %p %U %t %H %m %r %s %b %D'
    basedir: ./

logging:
  config: classpath:spring-log.xml