spring:
  data:
    mongodb:
      database: qipai_biji
      host: 172.19.24.161
      port: 27017
      username: root
      password: 'meiyoumima'
#      host: dds-bp1f74084c1cd354118530.mongodb.rds.aliyuncs.com
#      port: 3717
#      username: root
#      password: 'Meiyoumima!'
#      host: 121.196.23.189
#      port: 27025
#      username: root
#      password: '123456'
      authentication-database: admin
      repositories:
        enabled: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          bijiGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          bijiResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wisecrack:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          watchRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384

      bindings:
        bijiGame:
          destination: bijiGame
          contentType: application/json
          producer:
            partitionCount: 1
        bijiResult:
          destination: bijiResult
          contentType: application/json
          producer:
            partitionCount: 1
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-biji
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        bijiGameRoom:
          destination: bijiGameRoom
          group: qipai-biji
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-biji
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wisecrack:
          destination: wisecrack
          contentType: application/json
          producer:
            partitionCount: 1
        watchRecord:
          destination: watchRecord
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-biji
server:
  port: 2005
#  context-path: /biji
  connectionTimeout: 65000
  tomcat:
    max-connections: 1024
    max-threads: 1024
    access-log-enabled: true
    access-log-pattern: '%a %h %A %p %U %t %H %m %r %s %b %D'
    basedir: ./
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  config: classpath:spring-log.xml