spring:
  data:
    mongodb:
      #      uri: mongodb://localhost:27017/qipai_tuidaohu
      database: qipai_tuidaohu
      host: 172.19.24.161
      port: 27017
      username: root
      password: 'meiyoumima'
#      host: dds-bp1f74084c1cd354118530.mongodb.rds.aliyuncs.com
#      port: 3717
#      username: root
#      password: 'Meiyoumima!'
#      host: 121.196.23.189
#      port: 27025
#      username: root
#      password: '123456'
      authentication-database: admin
      repositories:
        enabled: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          hongzhongMajiangGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          hongzhongMajiangResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wisecrack:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          watchRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        hongzhongMajiangGame:
          destination: hongzhongMajiangGame
          contentType: application/json
          producer:
            partitionCount: 1
        hongzhongMajiangResult:
          destination: hongzhongMajiangResult
          contentType: application/json
          producer:
            partitionCount: 1
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-tuidaohu
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        hongzhongMajiangGameRoom:
          destination: hongzhongMajiangGameRoom
          group: qipai-tuidaohu
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-tuidaohu
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wisecrack:
          destination: wisecrack
          contentType: application/json
          producer:
            partitionCount: 1
        watchRecord:
          destination: watchRecord
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-tuidaohu

server:
  port: 2011
#  context-path: /tuidaohu
  connectionTimeout: 6000
  tomcat:
    max-connections: 2048
    max-threads: 2048
    access-log-enabled: true
    access-log-pattern: '%a %h %A %p %U %t %H %m %r %s %b %D'
    basedir: ./

logging:
  config: classpath:spring-log.xml